In [1]:
import pandas as pd

# **making the dataset understandable**

In [2]:
from google.colab import drive
drive.mount('/content/drive')
%cd "/content/drive/My Drive/datasets"

Mounted at /content/drive
/content/drive/My Drive/datasets

In [3]:

fileNames = ['SeriesExport-08-05-2023-13-14-54.csv']

In [4]:
df = pd.read_csv('SeriesExport-08-05-2023-13-14-54.csv')
df

     Series Key          SEDS.NUETB.CA.A
0   Series Name  SEDS.NUETB.CA.A, annual
1         Units              Billion Btu
2     Frequency                        A
3    Start Date                     2021
4      End Date                     1960
..          ...                      ...
63         1964                     4369
64         1963                     2288
65         1962                       84
66         1961                       55
67         1960                        1

[68 rows x 2 columns]

No charts were generated by quickchart

In [22]:
for name in fileNames:
  df=pd.read_csv(name)
  rowName = df.columns[1::2]
  rowName = [string[5:10] for string in rowName]
  df = df[6:].reset_index(drop=True)
  colName = list(df['Series Key'])
  rowName.append("YEAR")
  rowValue = df.columns[1::2]
  newTempDf = {
    'YEAR': colName
  }

  for i in range(len(rowName)-1):
    newTempDf[rowName[i]] = list(df[rowValue[i]])

  cleanedDf = pd.DataFrame(newTempDf)
  filePath = "/content/drive/My Drive/cleaned data/{}".format(name)
  cleanedDf.to_csv(filePath, index=False)